### ISSUE TITLE
Various PHP extensions not installed

### ISSUE THREAD

**Issue by modernjess** [aws-samples/ec2-lamp-server#1]
It would appear that many of the PHP extensions specified in the 01_php_install phase of AmazonLinux-2023-LAMP-server.yaml  are missing.

From [cfn-init.log](https://github.com/aws-samples/ec2-lamp-server/files/14909950/cfn-init.log)
```
Error: Unable to find a match: php-apcu
Error: Unable to find a match: `php-igbinary`
Error: Unable to find a match: php-msgpack
Error: Unable to find a match: php-lzf
Error: Unable to find a match: php-zstd
Error: Unable to find a match: php-imagick
Error: Unable to find a match: php-redis
Error: Unable to find a match: php-memcached
Error: Unable to find a match: php-lz4
```

**Configuration**
Source template: [AmazonLinux-2023-LAMP-server.yaml](https://github.com/aws-samples/ec2-lamp-server/blob/03c8d5015a84820f1e4a42f126049a5468a4ebfb/AmazonLinux-2023-LAMP-server.yaml)
processorArchitecture: Graviton (arm64)
phpVersion: php8.2
instanceType: t4g.small
webOption : Apache
databaseOption: none

**Note**
As an aside, I love that this template exists, and have been working with it extensively over the last week. It's been hugely helpful for me to come up to speed on CloudFormation templates.

**Comment by modernjess** [comment]
This might be a non-issue. Investigating further, it looks like the php modules are in fact present -- maybe through another package?

```
[ec2-user@ip-172-31-1-86 log]$ php -m
[PHP Modules]
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
enchant
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
imagick
intl
json
ldap
libxml
lz4
lzf
mbstring
memcached
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
pspell
random
readline
redis
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib
zstd

[Zend Modules]
Zend OPcache

```

**Comment by limmike** [comment]
Thanks for the report, and happy to know that you find it useful.

Some of the PHP extensions are currently not available from AL2023 repository, but may be available in future.
As such, I have make my php extension installation code future proof.  

To illustrate,  we use php-apcu code block as an example (reproduced below with line number)
```
1. # https://github.com/amazonlinux/amazon-linux-2023/issues/206
2. # php-apcu: https://github.com/krakjoe/apcu/blob/master/package.xml
3. dnf install -q -y php-apcu
4. if (! php -m | grep -q apcu); then
5.       yes 'no' | pecl install --configureoptions 'enable-apcu-debug="no"' apcu
6.       echo 'extension=apcu.so' > /etc/php.d/42-apcu.ini
7. fi
```

Line 1 links to AL2023 [Github issue](https://github.com/amazonlinux/amazon-linux-2023/issues/206) about php-apcu package request.  It allows us to visit that page for updates. Currently, the issue is open. It may be closed if AL2023 team release php-apcu package in future. 

Line 3 attempts to install php-apcu package from AL2023 repository. The package is not available as of today, hence the error  `Error: Unable to find a match: php-apcu`. 

Line 4 checks if apcu extension is installed using `php -m`. If not, line 5 use [PECL](https://www.php.net/manual/en/install.pecl.pear.php) to compile APCU extension. Line 2 links to APCU PECL `configureoption` for reference. 

Hope this clarifies.

Since you are learning CloudFormation, you can try the workshop at [https://cfn101.workshop.aws/](https://cfn101.workshop.aws/)

**Comment by modernjess** [comment]
Got it, understood. Thanks for the clarification.
